<h2 align='center' style='color:purple'>Finding best model and hyper parameter tunning using GridSearchCV</h2>

**Load iris flower dataset**

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
from sklearn import datasets
iris = datasets.load_iris()
iris

{'data': array([[5.1, 3.5, 1.4, 0.2],
        [4.9, 3. , 1.4, 0.2],
        [4.7, 3.2, 1.3, 0.2],
        [4.6, 3.1, 1.5, 0.2],
        [5. , 3.6, 1.4, 0.2],
        [5.4, 3.9, 1.7, 0.4],
        [4.6, 3.4, 1.4, 0.3],
        [5. , 3.4, 1.5, 0.2],
        [4.4, 2.9, 1.4, 0.2],
        [4.9, 3.1, 1.5, 0.1],
        [5.4, 3.7, 1.5, 0.2],
        [4.8, 3.4, 1.6, 0.2],
        [4.8, 3. , 1.4, 0.1],
        [4.3, 3. , 1.1, 0.1],
        [5.8, 4. , 1.2, 0.2],
        [5.7, 4.4, 1.5, 0.4],
        [5.4, 3.9, 1.3, 0.4],
        [5.1, 3.5, 1.4, 0.3],
        [5.7, 3.8, 1.7, 0.3],
        [5.1, 3.8, 1.5, 0.3],
        [5.4, 3.4, 1.7, 0.2],
        [5.1, 3.7, 1.5, 0.4],
        [4.6, 3.6, 1. , 0.2],
        [5.1, 3.3, 1.7, 0.5],
        [4.8, 3.4, 1.9, 0.2],
        [5. , 3. , 1.6, 0.2],
        [5. , 3.4, 1.6, 0.4],
        [5.2, 3.5, 1.5, 0.2],
        [5.2, 3.4, 1.4, 0.2],
        [4.7, 3.2, 1.6, 0.2],
        [4.8, 3.1, 1.6, 0.2],
        [5.4, 3.4, 1.5, 0.4],
        [5.2, 4.1, 1.5, 0.1],
  

In [5]:
df = pd.DataFrame(data=iris.data,columns=iris.feature_names)
df

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                  5.1               3.5                1.4               0.2
1                  4.9               3.0                1.4               0.2
2                  4.7               3.2                1.3               0.2
3                  4.6               3.1                1.5               0.2
4                  5.0               3.6                1.4               0.2
..                 ...               ...                ...               ...
145                6.7               3.0                5.2               2.3
146                6.3               2.5                5.0               1.9
147                6.5               3.0                5.2               2.0
148                6.2               3.4                5.4               2.3
149                5.9               3.0                5.1               1.8

[150 rows x 4 columns]

In [6]:
df['flower']=iris.target
df

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                  5.1               3.5                1.4               0.2   
1                  4.9               3.0                1.4               0.2   
2                  4.7               3.2                1.3               0.2   
3                  4.6               3.1                1.5               0.2   
4                  5.0               3.6                1.4               0.2   
..                 ...               ...                ...               ...   
145                6.7               3.0                5.2               2.3   
146                6.3               2.5                5.0               1.9   
147                6.5               3.0                5.2               2.0   
148                6.2               3.4                5.4               2.3   
149                5.9               3.0                5.1               1.8   

     flower  
0         0  
1         0  
2         0  
3         0  
4         0  
..      ...  
145       2  
146       2  
147       2  
148       2  
149       2  

[150 rows x 5 columns]

In [7]:
df.loc[df["flower"]==0,["flower"]]="setosa"
df.loc[df["flower"]==1,["flower"]]="versicolor"
df.loc[df["flower"]==2,["flower"]]="virginica" 
df

C:\Users\HP\AppData\Local\Temp\ipykernel_2960\702173314.py:1: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value 'setosa' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  df.loc[df["flower"]==0,["flower"]]="setosa"


sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                  5.1               3.5                1.4               0.2   
1                  4.9               3.0                1.4               0.2   
2                  4.7               3.2                1.3               0.2   
3                  4.6               3.1                1.5               0.2   
4                  5.0               3.6                1.4               0.2   
..                 ...               ...                ...               ...   
145                6.7               3.0                5.2               2.3   
146                6.3               2.5                5.0               1.9   
147                6.5               3.0                5.2               2.0   
148                6.2               3.4                5.4               2.3   
149                5.9               3.0                5.1               1.8   

        flower  
0       setosa  
1       setosa  
2       setosa  
3       setosa  
4       setosa  
..         ...  
145  virginica  
146  virginica  
147  virginica  
148  virginica  
149  virginica  

[150 rows x 5 columns]

<h3 style='color:blue'>Approach 1: Use train_test_split and manually tune parameters by trial and error</h3>

In [8]:
x = df.drop('flower', axis=1)
x

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                  5.1               3.5                1.4               0.2
1                  4.9               3.0                1.4               0.2
2                  4.7               3.2                1.3               0.2
3                  4.6               3.1                1.5               0.2
4                  5.0               3.6                1.4               0.2
..                 ...               ...                ...               ...
145                6.7               3.0                5.2               2.3
146                6.3               2.5                5.0               1.9
147                6.5               3.0                5.2               2.0
148                6.2               3.4                5.4               2.3
149                5.9               3.0                5.1               1.8

[150 rows x 4 columns]

In [9]:
y = df['flower']
y

0         setosa
1         setosa
2         setosa
3         setosa
4         setosa
         ...    
145    virginica
146    virginica
147    virginica
148    virginica
149    virginica
Name: flower, Length: 150, dtype: object

In [10]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(x, y, test_size=0.3)

In [11]:
X_train

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
10                 5.4               3.7                1.5               0.2
29                 4.7               3.2                1.6               0.2
114                5.8               2.8                5.1               2.4
72                 6.3               2.5                4.9               1.5
61                 5.9               3.0                4.2               1.5
..                 ...               ...                ...               ...
104                6.5               3.0                5.8               2.2
71                 6.1               2.8                4.0               1.3
146                6.3               2.5                5.0               1.9
55                 5.7               2.8                4.5               1.3
48                 5.3               3.7                1.5               0.2

[105 rows x 4 columns]

In [12]:
X_test

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
131                7.9               3.8                6.4               2.0
13                 4.3               3.0                1.1               0.1
62                 6.0               2.2                4.0               1.0
76                 6.8               2.8                4.8               1.4
34                 4.9               3.1                1.5               0.2
81                 5.5               2.4                3.7               1.0
136                6.3               3.4                5.6               2.4
7                  5.0               3.4                1.5               0.2
40                 5.0               3.5                1.3               0.3
108                6.7               2.5                5.8               1.8
36                 5.5               3.5                1.3               0.2
99                 5.7               2.8                4.1               1.3
66                 5.6               3.0                4.5               1.5
105                7.6               3.0                6.6               2.1
139                6.9               3.1                5.4               2.1
59                 5.2               2.7                3.9               1.4
115                6.4               3.2                5.3               2.3
69                 5.6               2.5                3.9               1.1
122                7.7               2.8                6.7               2.0
123                6.3               2.7                4.9               1.8
33                 5.5               4.2                1.4               0.2
56                 6.3               3.3                4.7               1.6
120                6.9               3.2                5.7               2.3
54                 6.5               2.8                4.6               1.5
78                 6.0               2.9                4.5               1.5
53                 5.5               2.3                4.0               1.3
28                 5.2               3.4                1.4               0.2
3                  4.6               3.1                1.5               0.2
90                 5.5               2.6                4.4               1.2
1                  4.9               3.0                1.4               0.2
60                 5.0               2.0                3.5               1.0
102                7.1               3.0                5.9               2.1
39                 5.1               3.4                1.5               0.2
135                7.7               3.0                6.1               2.3
85                 6.0               3.4                4.5               1.6
98                 5.1               2.5                3.0               1.1
111                6.4               2.7                5.3               1.9
129                7.2               3.0                5.8               1.6
41                 4.5               2.3                1.3               0.3
31                 5.4               3.4                1.5               0.4
142                5.8               2.7                5.1               1.9
125                7.2               3.2                6.0               1.8
52                 6.9               3.1                4.9               1.5
23                 5.1               3.3                1.7               0.5
86                 6.7               3.1                4.7               1.5

In [18]:
from sklearn.svm import SVC

In [18]:
from sklearn.svm import SVC

model = SVC(kernel='rbf', C=1, gamma='auto')

model.fit(X_train, y_train)

model.score(X_test, y_test)

1.0

<h3 style='color:blue'>Approach 2: Use K Fold Cross validation</h3>

**Manually try suppling models with different parameters to cross_val_score function with 5 fold cross validation**

In [19]:
from sklearn.model_selection import cross_val_score

In [20]:
sv1=cross_val_score(SVC(kernel='rbf',C=1,gamma='auto'),x, y, cv=5)
sv1

array([0.96666667, 1.        , 0.96666667, 0.96666667, 1.        ])

In [21]:
sv1.mean()

np.float64(0.9800000000000001)

In [22]:
sv2=cross_val_score(SVC(kernel='poly',C=1,gamma='auto'),x, y, cv=5)
sv2

array([1.        , 1.        , 0.9       , 0.93333333, 1.        ])

In [23]:
sv2.mean()

np.float64(0.9666666666666666)

In [24]:
sv3=cross_val_score(SVC(kernel='rbf',C=20,gamma='auto'),x, y, cv=5)
sv3

array([0.96666667, 1.        , 0.9       , 0.96666667, 1.        ])

In [25]:
sv3.mean()

np.float64(0.9666666666666668)

In [26]:
from sklearn.tree import DecisionTreeClassifier

In [27]:
sv3 = cross_val_score(DecisionTreeClassifier(), x, y, cv=5)
sv3

array([0.96666667, 0.96666667, 0.9       , 0.96666667, 1.        ])

In [28]:
sv3.mean()

np.float64(0.9600000000000002)

In [29]:
from sklearn.naive_bayes import GaussianNB

In [30]:
sv3 = cross_val_score(GaussianNB(), x, y, cv=5)
sv3

array([0.93333333, 0.96666667, 0.93333333, 0.93333333, 1.        ])

In [31]:
sv3.mean()

np.float64(0.9533333333333334)

In [32]:
from sklearn.neighbors import KNeighborsClassifier

In [33]:
sv4 = cross_val_score(KNeighborsClassifier(n_neighbors=3), x, y, cv=5)
sv4

array([0.96666667, 0.96666667, 0.93333333, 0.96666667, 1.        ])

In [34]:
sv4.mean()

np.float64(0.9666666666666668)

<h3 style='color:blue'>Use GridSearchCV</h3>

**GridSearchCV does exactly same thing as for loop above but in a single line of code**

In [35]:
from sklearn.model_selection import GridSearchCV

In [36]:
# clf = classifier

clf = GridSearchCV(SVC(), {
    'gamma': ['auto','scale'],   
    'C': [1,10,20,30],
    'kernel': ['rbf','linear', 'poly']
}, cv=5)

clf.fit(x, y)

clf.cv_results_

c:\Users\HP\AppData\Local\Programs\Python\Python312\Lib\site-packages\numpy\ma\core.py:2846: RuntimeWarning: invalid value encountered in cast
  _data = np.array(data, dtype=dtype, copy=copy,


{'mean_fit_time': array([0.00613823, 0.00479932, 0.00402927, 0.00395041, 0.00399289,
        0.00273538, 0.00237007, 0.00482025, 0.00952253, 0.00424299,
        0.00244532, 0.00489535, 0.00334826, 0.00194216, 0.01396856,
        0.00288343, 0.00221643, 0.00779333, 0.00232949, 0.0021874 ,
        0.01987081, 0.00197463, 0.0023881 , 0.00508518]),
 'std_fit_time': array([0.00120044, 0.00277137, 0.00332814, 0.00414684, 0.00303808,
        0.0036532 , 0.00232777, 0.00320611, 0.00586094, 0.00331895,
        0.00149951, 0.00304845, 0.004105  , 0.00176574, 0.00982385,
        0.00193886, 0.00208497, 0.00504695, 0.00207126, 0.00194901,
        0.0124404 , 0.00174813, 0.00201134, 0.00288385]),
 'mean_score_time': array([0.00480628, 0.00476336, 0.00347929, 0.00292358, 0.00257339,
        0.00038247, 0.0029448 , 0.00153666, 0.00229259, 0.00222659,
        0.00384812, 0.00096722, 0.00242071, 0.00398531, 0.00046453,
        0.00026636, 0.00291672, 0.00108728, 0.00369115, 0.00141215,
        0.003386

In [37]:
df = pd.DataFrame(clf.cv_results_)
df

mean_fit_time  std_fit_time  mean_score_time  std_score_time  param_C  \
0        0.006138      0.001200         0.004806        0.001847        1   
1        0.004799      0.002771         0.004763        0.003957        1   
2        0.004029      0.003328         0.003479        0.001937        1   
3        0.003950      0.004147         0.002924        0.003106        1   
4        0.003993      0.003038         0.002573        0.004283        1   
5        0.002735      0.003653         0.000382        0.000765        1   
6        0.002370      0.002328         0.002945        0.003419       10   
7        0.004820      0.003206         0.001537        0.001936       10   
8        0.009523      0.005861         0.002293        0.002523       10   
9        0.004243      0.003319         0.002227        0.001572       10   
10       0.002445      0.001500         0.003848        0.002576       10   
11       0.004895      0.003048         0.000967        0.001192       10   
12       0.003348      0.004105         0.002421        0.002587       20   
13       0.001942      0.001766         0.003985        0.003999       20   
14       0.013969      0.009824         0.000465        0.000929       20   
15       0.002883      0.001939         0.000266        0.000533       20   
16       0.002216      0.002085         0.002917        0.002792       20   
17       0.007793      0.005047         0.001087        0.001335       20   
18       0.002329      0.002071         0.003691        0.002096       30   
19       0.002187      0.001949         0.001412        0.001874       30   
20       0.019871      0.012440         0.003387        0.001116       30   
21       0.001975      0.001748         0.004563        0.004759       30   
22       0.002388      0.002011         0.004410        0.002685       30   
23       0.005085      0.002884         0.003023        0.001600       30   

   param_gamma param_kernel                                           params  \
0         auto          rbf       {'C': 1, 'gamma': 'auto', 'kernel': 'rbf'}   
1         auto       linear    {'C': 1, 'gamma': 'auto', 'kernel': 'linear'}   
2         auto         poly      {'C': 1, 'gamma': 'auto', 'kernel': 'poly'}   
3        scale          rbf      {'C': 1, 'gamma': 'scale', 'kernel': 'rbf'}   
4        scale       linear   {'C': 1, 'gamma': 'scale', 'kernel': 'linear'}   
5        scale         poly     {'C': 1, 'gamma': 'scale', 'kernel': 'poly'}   
6         auto          rbf      {'C': 10, 'gamma': 'auto', 'kernel': 'rbf'}   
7         auto       linear   {'C': 10, 'gamma': 'auto', 'kernel': 'linear'}   
8         auto         poly     {'C': 10, 'gamma': 'auto', 'kernel': 'poly'}   
9        scale          rbf     {'C': 10, 'gamma': 'scale', 'kernel': 'rbf'}   
10       scale       linear  {'C': 10, 'gamma': 'scale', 'kernel': 'linear'}   
11       scale         poly    {'C': 10, 'gamma': 'scale', 'kernel': 'poly'}   
12        auto          rbf      {'C': 20, 'gamma': 'auto', 'kernel': 'rbf'}   
13        auto       linear   {'C': 20, 'gamma': 'auto', 'kernel': 'linear'}   
14        auto         poly     {'C': 20, 'gamma': 'auto', 'kernel': 'poly'}   
15       scale          rbf     {'C': 20, 'gamma': 'scale', 'kernel': 'rbf'}   
16       scale       linear  {'C': 20, 'gamma': 'scale', 'kernel': 'linear'}   
17       scale         poly    {'C': 20, 'gamma': 'scale', 'kernel': 'poly'}   
18        auto          rbf      {'C': 30, 'gamma': 'auto', 'kernel': 'rbf'}   
19        auto       linear   {'C': 30, 'gamma': 'auto', 'kernel': 'linear'}   
20        auto         poly     {'C': 30, 'gamma': 'auto', 'kernel': 'poly'}   
21       scale          rbf     {'C': 30, 'gamma': 'scale', 'kernel': 'rbf'}   
22       scale       linear  {'C': 30, 'gamma': 'scale', 'kernel': 'linear'}   
23       scale         poly    {'C': 30, 'gamma': 'scale', 'kernel': 'poly'}   

    split0_test_score  split1_test_score  split2_test_score  \
0            0

In [38]:
df[['param_C','param_kernel','mean_test_score']]

param_C param_kernel  mean_test_score
0         1          rbf         0.980000
1         1       linear         0.980000
2         1         poly         0.966667
3         1          rbf         0.966667
4         1       linear         0.980000
5         1         poly         0.980000
6        10          rbf         0.980000
7        10       linear         0.973333
8        10         poly         0.966667
9        10          rbf         0.980000
10       10       linear         0.973333
11       10         poly         0.966667
12       20          rbf         0.966667
13       20       linear         0.966667
14       20         poly         0.953333
15       20          rbf         0.980000
16       20       linear         0.966667
17       20         poly         0.966667
18       30          rbf         0.960000
19       30       linear         0.960000
20       30         poly         0.953333
21       30          rbf         0.973333
22       30       linear         0.960000
23       30         poly         0.966667

In [39]:
clf.best_params_

{'C': 1, 'gamma': 'auto', 'kernel': 'rbf'}

In [40]:
clf.best_score_

np.float64(0.9800000000000001)

In [43]:
df = pd.read_csv(r"E:\DS_Notekhata\15-SVM\Breast_Cancer_Diagnostic.csv")

In [44]:
df

radius_mean  texture_mean  perimeter_mean  area_mean  smoothness_mean  \
0          17.99         10.38          122.80     1001.0          0.11840   
1          20.57         17.77          132.90     1326.0          0.08474   
2          19.69         21.25          130.00     1203.0          0.10960   
3          11.42         20.38           77.58      386.1          0.14250   
4          20.29         14.34          135.10     1297.0          0.10030   
..           ...           ...             ...        ...              ...   
564        21.56         22.39          142.00     1479.0          0.11100   
565        20.13         28.25          131.20     1261.0          0.09780   
566        16.60         28.08          108.30      858.1          0.08455   
567        20.60         29.33          140.10     1265.0          0.11780   
568         7.76         24.54           47.92      181.0          0.05263   

     compactness_mean  concavity_mean  concave points_mean  symmetry_mean  \
0             0.27760         0.30010              0.14710         0.2419   
1             0.07864         0.08690              0.07017         0.1812   
2             0.15990         0.19740              0.12790         0.2069   
3             0.28390         0.24140              0.10520         0.2597   
4             0.13280         0.19800              0.10430         0.1809   
..                ...             ...                  ...            ...   
564           0.11590         0.24390              0.13890         0.1726   
565           0.10340         0.14400              0.09791         0.1752   
566           0.10230         0.09251              0.05302         0.1590   
567           0.27700         0.35140              0.15200         0.2397   
568           0.04362         0.00000              0.00000         0.1587   

     fractal_dimension_mean diagnosis  
0                   0.07871         M  
1                   0.05667         M  
2                   0.05999         M  
3                   0.09744         M  
4                   0.05883         M  
..                      ...       ...  
564                 0.05623         M  
565                 0.05533         M  
566                 0.05648         M  
567                 0.07016         M  
568                 0.05884         B  

[569 rows x 11 columns]

In [45]:
x = df.drop('diagnosis', axis = 1)
y = df['diagnosis']

In [46]:
from sklearn.preprocessing import MinMaxScaler

MMS = MinMaxScaler()

x_scaler = MMS.fit_transform(x)

x_scaler

array([[0.52103744, 0.0226581 , 0.54598853, ..., 0.73111332, 0.68636364,
        0.60551811],
       [0.64314449, 0.27257355, 0.61578329, ..., 0.34875746, 0.37979798,
        0.14132266],
       [0.60149557, 0.3902604 , 0.59574321, ..., 0.63568588, 0.50959596,
        0.21124684],
       ...,
       [0.45525108, 0.62123774, 0.44578813, ..., 0.26351889, 0.26767677,
        0.13732098],
       [0.64456434, 0.66351031, 0.66553797, ..., 0.7554672 , 0.67525253,
        0.42544229],
       [0.03686876, 0.50152181, 0.02853984, ..., 0.        , 0.26616162,
        0.18702612]])

In [47]:

clf = GridSearchCV(SVC(), {
    'gamma': ['auto','scale'],   
    'C': [1,10,20,30],
    'kernel': ['rbf','linear', 'poly']
}, cv=5)

clf.fit(x_scaler, y)

clf.cv_results_

c:\Users\HP\AppData\Local\Programs\Python\Python312\Lib\site-packages\numpy\ma\core.py:2846: RuntimeWarning: invalid value encountered in cast
  _data = np.array(data, dtype=dtype, copy=copy,


{'mean_fit_time': array([0.00996003, 0.00834484, 0.0079011 , 0.00599222, 0.00303545,
        0.00786471, 0.0060113 , 0.00661926, 0.00608678, 0.00713701,
        0.00564919, 0.01140246, 0.00317378, 0.00564752, 0.00606289,
        0.00754924, 0.0049396 , 0.02505407, 0.00632305, 0.00761504,
        0.00613961, 0.00763321, 0.00504093, 0.03025007]),
 'std_fit_time': array([0.00114503, 0.00282895, 0.0035615 , 0.00259227, 0.00176458,
        0.00232351, 0.00188629, 0.00187795, 0.00084094, 0.00275889,
        0.00224471, 0.00195149, 0.00166296, 0.00531243, 0.00392043,
        0.00520126, 0.00255669, 0.00564228, 0.00079771, 0.00322207,
        0.00350385, 0.00237396, 0.00361126, 0.01083479]),
 'mean_score_time': array([0.01527982, 0.00329018, 0.00288491, 0.00327363, 0.00236163,
        0.00102906, 0.00316596, 0.0013371 , 0.00235538, 0.00105896,
        0.00021157, 0.00232549, 0.00297337, 0.00099444, 0.00091724,
        0.00433693, 0.00212808, 0.00233998, 0.00314388, 0.00124531,
        0.003443

In [48]:
df =pd.DataFrame(clf.cv_results_)
df

mean_fit_time  std_fit_time  mean_score_time  std_score_time  param_C  \
0        0.009960      0.001145         0.015280        0.016322        1   
1        0.008345      0.002829         0.003290        0.001036        1   
2        0.007901      0.003562         0.002885        0.002378        1   
3        0.005992      0.002592         0.003274        0.002483        1   
4        0.003035      0.001765         0.002362        0.003194        1   
5        0.007865      0.002324         0.001029        0.000895        1   
6        0.006011      0.001886         0.003166        0.001901       10   
7        0.006619      0.001878         0.001337        0.001127       10   
8        0.006087      0.000841         0.002355        0.001382       10   
9        0.007137      0.002759         0.001059        0.001603       10   
10       0.005649      0.002245         0.000212        0.000423       10   
11       0.011402      0.001951         0.002325        0.000645       10   
12       0.003174      0.001663         0.002973        0.002626       20   
13       0.005648      0.005312         0.000994        0.001256       20   
14       0.006063      0.003920         0.000917        0.001834       20   
15       0.007549      0.005201         0.004337        0.003447       20   
16       0.004940      0.002557         0.002128        0.003148       20   
17       0.025054      0.005642         0.002340        0.002175       20   
18       0.006323      0.000798         0.003144        0.000740       30   
19       0.007615      0.003222         0.001245        0.000848       30   
20       0.006140      0.003504         0.003443        0.003380       30   
21       0.007633      0.002374         0.002422        0.002994       30   
22       0.005041      0.003611         0.004095        0.002677       30   
23       0.030250      0.010835         0.004472        0.003572       30   

   param_gamma param_kernel                                           params  \
0         auto          rbf       {'C': 1, 'gamma': 'auto', 'kernel': 'rbf'}   
1         auto       linear    {'C': 1, 'gamma': 'auto', 'kernel': 'linear'}   
2         auto         poly      {'C': 1, 'gamma': 'auto', 'kernel': 'poly'}   
3        scale          rbf      {'C': 1, 'gamma': 'scale', 'kernel': 'rbf'}   
4        scale       linear   {'C': 1, 'gamma': 'scale', 'kernel': 'linear'}   
5        scale         poly     {'C': 1, 'gamma': 'scale', 'kernel': 'poly'}   
6         auto          rbf      {'C': 10, 'gamma': 'auto', 'kernel': 'rbf'}   
7         auto       linear   {'C': 10, 'gamma': 'auto', 'kernel': 'linear'}   
8         auto         poly     {'C': 10, 'gamma': 'auto', 'kernel': 'poly'}   
9        scale          rbf     {'C': 10, 'gamma': 'scale', 'kernel': 'rbf'}   
10       scale       linear  {'C': 10, 'gamma': 'scale', 'kernel': 'linear'}   
11       scale         poly    {'C': 10, 'gamma': 'scale', 'kernel': 'poly'}   
12        auto          rbf      {'C': 20, 'gamma': 'auto', 'kernel': 'rbf'}   
13        auto       linear   {'C': 20, 'gamma': 'auto', 'kernel': 'linear'}   
14        auto         poly     {'C': 20, 'gamma': 'auto', 'kernel': 'poly'}   
15       scale          rbf     {'C': 20, 'gamma': 'scale', 'kernel': 'rbf'}   
16       scale       linear  {'C': 20, 'gamma': 'scale', 'kernel': 'linear'}   
17       scale         poly    {'C': 20, 'gamma': 'scale', 'kernel': 'poly'}   
18        auto          rbf      {'C': 30, 'gamma': 'auto', 'kernel': 'rbf'}   
19        auto       linear   {'C': 30, 'gamma': 'auto', 'kernel': 'linear'}   
20        auto         poly     {'C': 30, 'gamma': 'auto', 'kernel': 'poly'}   
21       scale          rbf     {'C': 30, 'gamma': 'scale', 'kernel': 'rbf'}   
22       scale       linear  {'C': 30, 'gamma': 'scale', 'kernel': 'linear'}   
23       scale         poly    {'C': 30, 'gamma': 'scale', 'kernel': 'poly'}   

    split0_test_score  split1_test_score  split2_test_score  \
0            0

In [49]:
clf.best_params_

{'C': 10, 'gamma': 'scale', 'kernel': 'poly'}

In [50]:
clf.best_score_

np.float64(0.9543238627542306)