## Identifying Best Value Of k

In [2]:
import pandas as pd
from sklearn import datasets
from sklearn.preprocessing import StandardScaler
from sklearn.pipeline import Pipeline

In [3]:
iris = datasets.load_iris()
iris

{'data': array([[5.1, 3.5, 1.4, 0.2],
        [4.9, 3. , 1.4, 0.2],
        [4.7, 3.2, 1.3, 0.2],
        [4.6, 3.1, 1.5, 0.2],
        [5. , 3.6, 1.4, 0.2],
        [5.4, 3.9, 1.7, 0.4],
        [4.6, 3.4, 1.4, 0.3],
        [5. , 3.4, 1.5, 0.2],
        [4.4, 2.9, 1.4, 0.2],
        [4.9, 3.1, 1.5, 0.1],
        [5.4, 3.7, 1.5, 0.2],
        [4.8, 3.4, 1.6, 0.2],
        [4.8, 3. , 1.4, 0.1],
        [4.3, 3. , 1.1, 0.1],
        [5.8, 4. , 1.2, 0.2],
        [5.7, 4.4, 1.5, 0.4],
        [5.4, 3.9, 1.3, 0.4],
        [5.1, 3.5, 1.4, 0.3],
        [5.7, 3.8, 1.7, 0.3],
        [5.1, 3.8, 1.5, 0.3],
        [5.4, 3.4, 1.7, 0.2],
        [5.1, 3.7, 1.5, 0.4],
        [4.6, 3.6, 1. , 0.2],
        [5.1, 3.3, 1.7, 0.5],
        [4.8, 3.4, 1.9, 0.2],
        [5. , 3. , 1.6, 0.2],
        [5. , 3.4, 1.6, 0.4],
        [5.2, 3.5, 1.5, 0.2],
        [5.2, 3.4, 1.4, 0.2],
        [4.7, 3.2, 1.6, 0.2],
        [4.8, 3.1, 1.6, 0.2],
        [5.4, 3.4, 1.5, 0.4],
        [5.2, 4.1, 1.5, 0.1],
  

In [4]:
df = pd.DataFrame(data=iris.data, columns = iris.feature_names)
df['target'] = iris.target
df

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                  5.1               3.5                1.4               0.2   
1                  4.9               3.0                1.4               0.2   
2                  4.7               3.2                1.3               0.2   
3                  4.6               3.1                1.5               0.2   
4                  5.0               3.6                1.4               0.2   
..                 ...               ...                ...               ...   
145                6.7               3.0                5.2               2.3   
146                6.3               2.5                5.0               1.9   
147                6.5               3.0                5.2               2.0   
148                6.2               3.4                5.4               2.3   
149                5.9               3.0                5.1               1.8   

     target  
0         0  
1         0  
2         0  
3         0  
4         0  
..      ...  
145       2  
146       2  
147       2  
148       2  
149       2  

[150 rows x 5 columns]

In [5]:
X = iris.data
y = iris.target

X

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3

In [6]:
y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [7]:
standardizer = StandardScaler()

X_std = standardizer.fit_transform(X)
X_std

array([[-9.00681170e-01,  1.01900435e+00, -1.34022653e+00,
        -1.31544430e+00],
       [-1.14301691e+00, -1.31979479e-01, -1.34022653e+00,
        -1.31544430e+00],
       [-1.38535265e+00,  3.28414053e-01, -1.39706395e+00,
        -1.31544430e+00],
       [-1.50652052e+00,  9.82172869e-02, -1.28338910e+00,
        -1.31544430e+00],
       [-1.02184904e+00,  1.24920112e+00, -1.34022653e+00,
        -1.31544430e+00],
       [-5.37177559e-01,  1.93979142e+00, -1.16971425e+00,
        -1.05217993e+00],
       [-1.50652052e+00,  7.88807586e-01, -1.34022653e+00,
        -1.18381211e+00],
       [-1.02184904e+00,  7.88807586e-01, -1.28338910e+00,
        -1.31544430e+00],
       [-1.74885626e+00, -3.62176246e-01, -1.34022653e+00,
        -1.31544430e+00],
       [-1.14301691e+00,  9.82172869e-02, -1.28338910e+00,
        -1.44707648e+00],
       [-5.37177559e-01,  1.47939788e+00, -1.28338910e+00,
        -1.31544430e+00],
       [-1.26418478e+00,  7.88807586e-01, -1.22655167e+00,
      

In [8]:
from sklearn.model_selection import cross_val_score

In [9]:
from sklearn.neighbors import KNeighborsClassifier

In [10]:
sv1 = cross_val_score(KNeighborsClassifier(n_neighbors=2), X_std, y, cv=5)
sv1

array([0.96666667, 0.96666667, 0.9       , 0.9       , 1.        ])

In [11]:
sv1.mean()

np.float64(0.9466666666666667)

In [12]:
sv1 = cross_val_score(KNeighborsClassifier(n_neighbors=6), X_std, y, cv=5)
sv1

array([0.96666667, 0.96666667, 1.        , 0.9       , 1.        ])

In [13]:
sv1.mean()

np.float64(0.9666666666666668)

In [14]:
from sklearn.model_selection import GridSearchCV

In [15]:
clf = GridSearchCV(KNeighborsClassifier(), {
    'n_neighbors': [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
}, cv=5)

clf.fit(X_std, y)

c:\Users\HP\AppData\Local\Programs\Python\Python312\Lib\site-packages\numpy\ma\core.py:2846: RuntimeWarning: invalid value encountered in cast
  _data = np.array(data, dtype=dtype, copy=copy,


GridSearchCV(cv=5, estimator=KNeighborsClassifier(),
             param_grid={'n_neighbors': [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]})

In [16]:
clf.cv_results_

{'mean_fit_time': array([0.00183005, 0.00187845, 0.00116143, 0.00176501, 0.00211625,
        0.00251112, 0.000386  , 0.00107884, 0.0015367 , 0.00064311]),
 'std_fit_time': array([0.00099752, 0.00128289, 0.00066755, 0.00197063, 0.00305778,
        0.00346652, 0.000772  , 0.00137422, 0.00188747, 0.0008558 ]),
 'mean_score_time': array([0.0103055 , 0.00700526, 0.00388961, 0.00374355, 0.00535107,
        0.00559516, 0.00602679, 0.00498323, 0.00337062, 0.00664067]),
 'std_score_time': array([0.00130571, 0.00377222, 0.00031319, 0.00327332, 0.00605325,
        0.00357067, 0.00423524, 0.00413897, 0.00307235, 0.00430517]),
 'param_n_neighbors': masked_array(data=[1, 2, 3, 4, 5, 6, 7, 8, 9, 10],
              mask=[False, False, False, False, False, False, False, False,
                    False, False],
        fill_value=999999),
 'params': [{'n_neighbors': 1},
  {'n_neighbors': 2},
  {'n_neighbors': 3},
  {'n_neighbors': 4},
  {'n_neighbors': 5},
  {'n_neighbors': 6},
  {'n_neighbors': 7},
  

In [17]:
import pandas as pd
df =pd.DataFrame(clf.cv_results_)
df

mean_fit_time  std_fit_time  mean_score_time  std_score_time  \
0       0.001830      0.000998         0.010306        0.001306   
1       0.001878      0.001283         0.007005        0.003772   
2       0.001161      0.000668         0.003890        0.000313   
3       0.001765      0.001971         0.003744        0.003273   
4       0.002116      0.003058         0.005351        0.006053   
5       0.002511      0.003467         0.005595        0.003571   
6       0.000386      0.000772         0.006027        0.004235   
7       0.001079      0.001374         0.004983        0.004139   
8       0.001537      0.001887         0.003371        0.003072   
9       0.000643      0.000856         0.006641        0.004305   

   param_n_neighbors               params  split0_test_score  \
0                  1   {'n_neighbors': 1}           0.933333   
1                  2   {'n_neighbors': 2}           0.966667   
2                  3   {'n_neighbors': 3}           0.966667   
3                  4   {'n_neighbors': 4}           0.966667   
4                  5   {'n_neighbors': 5}           0.966667   
5                  6   {'n_neighbors': 6}           0.966667   
6                  7   {'n_neighbors': 7}           0.966667   
7                  8   {'n_neighbors': 8}           0.966667   
8                  9   {'n_neighbors': 9}           0.966667   
9                 10  {'n_neighbors': 10}           0.966667   

   split1_test_score  split2_test_score  split3_test_score  split4_test_score  \
0           0.966667           0.933333           0.900000           1.000000   
1           0.966667           0.900000           0.900000           1.000000   
2           0.966667           0.933333           0.900000           1.000000   
3           0.966667           1.000000           0.866667           0.966667   
4           0.966667           0.933333           0.933333           1.000000   
5           0.966667           1.000000           0.900000           1.000000   
6           0.966667           0.933333           0.900000           1.000000   
7           0.966667           1.000000           0.933333           0.966667   
8           0.966667           0.966667           0.900000           1.000000   
9           0.966667           0.966667           0.933333           0.966667   

   mean_test_score  std_test_score  rank_test_score  
0         0.946667        0.033993               10  
1         0.946667        0.040000                9  
2         0.953333        0.033993                6  
3         0.953333        0.045216                6  
4         0.960000        0.024944                3  
5         0.966667        0.036515                1  
6         0.953333        0.033993                6  
7         0.966667        0.021082                1  
8         0.960000        0.032660                3  
9         0.960000        0.013333                3

In [18]:
clf.best_params_

{'n_neighbors': 6}

In [19]:
clf.best_score_

np.float64(0.9666666666666668)

In [20]:
sv1 = cross_val_score(KNeighborsClassifier(n_neighbors=6), X_std, y, cv=5)
sv1

array([0.96666667, 0.96666667, 1.        , 0.9       , 1.        ])

In [24]:
sv1.mean()

np.float64(0.9666666666666668)