# Support Vector Machines (SVMs) using scikit-learn in Python
Hi Guys,<br>

Welcome to the Support Vector Machines lecture using scikit-learn in Python.<br>

As suggested in the theory lecture, we are going to work with a real dataset on [Breast Cancer Wisconsin (Diagnostic)](https://www.kaggle.com/uciml/breast-cancer-wisconsin-data/data). <br><br>

<font style="font-size:12px;color:green;">&#9758; The dataset is available on kaggle and originally belong to [UCI Machine Learning Repository](https://archive.ics.uci.edu/ml/datasets/Breast+Cancer+Wisconsin+%28Diagnostic%29). This dataset was donated to UCI by Nick Street in 1995 for the public use. [Relevant Papers](https://archive.ics.uci.edu/ml/datasets/Breast+Cancer+Wisconsin+%28Diagnostic%29) and [detailed description](https://archive.ics.uci.edu/ml/machine-learning-databases/breast-cancer-wisconsin/wdbc.names) on the dataset is provided at UCI website.<br></font>

Because we have worked with this dataset in Logistic Regression and KNN sections, so, this will allow us to compare the SVM to those models. However, in the SVM project, we will work with another new and real life dataset on credit approval. <br>

&#9758; Breast cancer dataset can be loaded from Scikit-learn. Its up to you if you want to load from scikit-learn or use csv data file which is provided in the course material.<br>
I am going to load the one which is in the course material!<br>
First thing first, let's import some libraries!

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
df = pd.read_csv("Breast_Cancer_Diagnostic.csv")

In [3]:
df

radius_mean  texture_mean  perimeter_mean  area_mean  smoothness_mean  \
0          17.99         10.38          122.80     1001.0          0.11840   
1          20.57         17.77          132.90     1326.0          0.08474   
2          19.69         21.25          130.00     1203.0          0.10960   
3          11.42         20.38           77.58      386.1          0.14250   
4          20.29         14.34          135.10     1297.0          0.10030   
..           ...           ...             ...        ...              ...   
564        21.56         22.39          142.00     1479.0          0.11100   
565        20.13         28.25          131.20     1261.0          0.09780   
566        16.60         28.08          108.30      858.1          0.08455   
567        20.60         29.33          140.10     1265.0          0.11780   
568         7.76         24.54           47.92      181.0          0.05263   

     compactness_mean  concavity_mean  concave points_mean  symmetry_mean  \
0             0.27760         0.30010              0.14710         0.2419   
1             0.07864         0.08690              0.07017         0.1812   
2             0.15990         0.19740              0.12790         0.2069   
3             0.28390         0.24140              0.10520         0.2597   
4             0.13280         0.19800              0.10430         0.1809   
..                ...             ...                  ...            ...   
564           0.11590         0.24390              0.13890         0.1726   
565           0.10340         0.14400              0.09791         0.1752   
566           0.10230         0.09251              0.05302         0.1590   
567           0.27700         0.35140              0.15200         0.2397   
568           0.04362         0.00000              0.00000         0.1587   

     fractal_dimension_mean diagnosis  
0                   0.07871         M  
1                   0.05667         M  
2                   0.05999         M  
3                   0.09744         M  
4                   0.05883         M  
..                      ...       ...  
564                 0.05623         M  
565                 0.05533         M  
566                 0.05648         M  
567                 0.07016         M  
568                 0.05884         B  

[569 rows x 11 columns]

In [4]:
df.isnull().sum()

radius_mean               0
texture_mean              0
perimeter_mean            0
area_mean                 0
smoothness_mean           0
compactness_mean          0
concavity_mean            0
concave points_mean       0
symmetry_mean             0
fractal_dimension_mean    0
diagnosis                 0
dtype: int64

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 569 entries, 0 to 568
Data columns (total 11 columns):
 #   Column                  Non-Null Count  Dtype  
---  ------                  --------------  -----  
 0   radius_mean             569 non-null    float64
 1   texture_mean            569 non-null    float64
 2   perimeter_mean          569 non-null    float64
 3   area_mean               569 non-null    float64
 4   smoothness_mean         569 non-null    float64
 5   compactness_mean        569 non-null    float64
 6   concavity_mean          569 non-null    float64
 7   concave points_mean     569 non-null    float64
 8   symmetry_mean           569 non-null    float64
 9   fractal_dimension_mean  569 non-null    float64
 10  diagnosis               569 non-null    object 
dtypes: float64(10), object(1)
memory usage: 49.0+ KB


## Machine Learning 
### Train Test Split
I am sure, this is on your finger tips now!

In [6]:
X = df.drop('diagnosis', axis = 1)
y = df['diagnosis']

In [7]:
X

radius_mean  texture_mean  perimeter_mean  area_mean  smoothness_mean  \
0          17.99         10.38          122.80     1001.0          0.11840   
1          20.57         17.77          132.90     1326.0          0.08474   
2          19.69         21.25          130.00     1203.0          0.10960   
3          11.42         20.38           77.58      386.1          0.14250   
4          20.29         14.34          135.10     1297.0          0.10030   
..           ...           ...             ...        ...              ...   
564        21.56         22.39          142.00     1479.0          0.11100   
565        20.13         28.25          131.20     1261.0          0.09780   
566        16.60         28.08          108.30      858.1          0.08455   
567        20.60         29.33          140.10     1265.0          0.11780   
568         7.76         24.54           47.92      181.0          0.05263   

     compactness_mean  concavity_mean  concave points_mean  symmetry_mean  \
0             0.27760         0.30010              0.14710         0.2419   
1             0.07864         0.08690              0.07017         0.1812   
2             0.15990         0.19740              0.12790         0.2069   
3             0.28390         0.24140              0.10520         0.2597   
4             0.13280         0.19800              0.10430         0.1809   
..                ...             ...                  ...            ...   
564           0.11590         0.24390              0.13890         0.1726   
565           0.10340         0.14400              0.09791         0.1752   
566           0.10230         0.09251              0.05302         0.1590   
567           0.27700         0.35140              0.15200         0.2397   
568           0.04362         0.00000              0.00000         0.1587   

     fractal_dimension_mean  
0                   0.07871  
1                   0.05667  
2                   0.05999  
3                   0.09744  
4                   0.05883  
..                      ...  
564                 0.05623  
565                 0.05533  
566                 0.05648  
567                 0.07016  
568                 0.05884  

[569 rows x 10 columns]

In [8]:
y

0      M
1      M
2      M
3      M
4      M
      ..
564    M
565    M
566    M
567    M
568    B
Name: diagnosis, Length: 569, dtype: object

In [9]:
from sklearn.preprocessing import MinMaxScaler

MMS = MinMaxScaler()

x_scaler = MMS.fit_transform(X)

x_scaler

array([[0.52103744, 0.0226581 , 0.54598853, ..., 0.73111332, 0.68636364,
        0.60551811],
       [0.64314449, 0.27257355, 0.61578329, ..., 0.34875746, 0.37979798,
        0.14132266],
       [0.60149557, 0.3902604 , 0.59574321, ..., 0.63568588, 0.50959596,
        0.21124684],
       ...,
       [0.45525108, 0.62123774, 0.44578813, ..., 0.26351889, 0.26767677,
        0.13732098],
       [0.64456434, 0.66351031, 0.66553797, ..., 0.7554672 , 0.67525253,
        0.42544229],
       [0.03686876, 0.50152181, 0.02853984, ..., 0.        , 0.26616162,
        0.18702612]])

In [10]:
x_scaler.shape

(569, 10)

In [11]:
from sklearn.model_selection import train_test_split

In [12]:
X_train, X_test, y_train, y_test = train_test_split(x_scaler, y, test_size=0.20, random_state=42)

Few steps that you can lead me through now!
* Importing classifier, 
* creating instance, 
* train (fit) the model on training data and 
* do the predictions for test data, right? <br>

Let's do this step by step. Note, SVC (support vector classifier) is in the svm class!

### Importing and  training the Support Vector Classifier

In [13]:
X_train
#y_train

array([[0.09692839, 0.25769361, 0.10365559, ..., 0.21744533, 0.53080808,
        0.64237574],
       [0.66775522, 0.57017247, 0.68350494, ..., 0.74353877, 0.67424242,
        0.50589722],
       [0.10374367, 0.14034494, 0.10648884, ..., 0.1083499 , 0.6469697 ,
        0.4142797 ],
       ...,
       [0.34592267, 0.2404464 , 0.32140142, ..., 0.03106362, 0.22626263,
        0.0800337 ],
       [0.33125089, 0.33513696, 0.32706793, ..., 0.32122266, 0.30757576,
        0.32603201],
       [0.24605992, 0.36557322, 0.23101375, ..., 0.08797217, 0.34292929,
        0.14342881]])

In [14]:
X_train.shape

(455, 10)

In [15]:
X_test

array([[0.25978513, 0.30064254, 0.25775689, ..., 0.18991054, 0.43686869,
        0.29001685],
       [0.56599934, 0.39228948, 0.55151683, ..., 0.39517893, 0.26363636,
        0.09793597],
       [0.4012968 , 0.33040243, 0.40017967, ..., 0.40193837, 0.43989899,
        0.168492  ],
       ...,
       [0.21482323, 0.17653027, 0.207864  , ..., 0.14557654, 0.41565657,
        0.24684078],
       [0.34260968, 0.61345959, 0.33694976, ..., 0.21908549, 0.14242424,
        0.23862679],
       [0.65071702, 0.72404464, 0.63513233, ..., 0.42972167, 0.35808081,
        0.14279697]])

In [16]:
y_test

204    B
70     M
131    M
431    B
540    B
      ..
486    B
75     M
249    B
238    B
265    M
Name: diagnosis, Length: 114, dtype: object

In [17]:
from sklearn.svm import SVC
svm_model = SVC() #Default: kernel='rbf',C=1,gamma='scale'
svm_model.fit(X_train,y_train)

SVC()

In [18]:
svm_model.score(X_test, y_test)

0.9736842105263158

In [19]:
svm_model = SVC(kernel='linear',C=30,gamma='auto') #kernel{‘linear’, ‘poly’, ‘rbf’, ‘sigmoid’, ‘precomputed’} or callable, default=’rbf’
svm_model.fit(X_train,y_train)

SVC(C=30, gamma='auto', kernel='linear')

In [20]:
svm_model.score(X_test, y_test)

0.9298245614035088

In [21]:
from sklearn.model_selection import cross_val_score

In [22]:
sv1=cross_val_score(SVC(kernel='poly',C=10,gamma='scale'),x_scaler, y, cv=5)
sv1

array([0.93859649, 0.96491228, 0.94736842, 0.95614035, 0.96460177])

In [23]:
sv1.mean()

np.float64(0.9543238627542306)

In [24]:
sv1=cross_val_score(SVC(kernel='rbf',C=1,gamma='auto'),x_scaler, y, cv=5)
sv1

array([0.85964912, 0.92105263, 0.92982456, 0.93859649, 0.95575221])

In [25]:
sv1.mean()

np.float64(0.9209750038813848)

In [26]:
sv1=cross_val_score(SVC(kernel='linear',C=30,gamma='auto'),x_scaler, y, cv=5)
sv1

array([0.87719298, 0.92982456, 0.95614035, 0.95614035, 0.92035398])

In [27]:
sv1.mean()

np.float64(0.927930445582984)

## Excellent
We are done with SVMs, lets move on and practice the skills on another dataset.
